### ISSUE TITLE
Rx.models.show should be able to take something other than ID

### ISSUE THREAD

**Issue by lancejpollard** [dima/restfulx_framework#24]
Hey Dima,

I'm working with CouchDB through CouchRest, and I almost never am using the "id" property to retrieve objects.  Often times it's Page.by_title, Post.by_slug, Comment.by_author, etc....

I would like to be able to use the "show" method so I don't have to just add metadata all time, like:

Rx.models.show(Page, {metadata:{slug:"about"}});

... but I do realize that it might be too complex to try to make it so "id" could be customized in the "show" method.

What do you recommend/what are you ideas with this?  If I use "show" and pass metadata, it makes a url like:

/pages/null.json

 would rather it be something like

/pages/about.json

Any ideas on what I should add/change/do-differently to make this possible?  I'm eager to contribute!  Thanks!

Lance

**Comment by dima** [comment]
Hey Lance,

You might want to add another method to Rx.models.\* called Rx.models.showBy for example that does what you want and then play with RxUtils.nestURL method (don't remember what it's called right now), but there's one method that determines what URLs requests get resolved to. That way you might be able to do stuff like:

```
 Rx.models.show(Page, {by:{slug:"about"}});

 Rx.models.showBy({slug:"about"}, Page);
```

Or you could make "id" in your model customizable. Fundamentally it doesn't need to be "id" it can be anything. You'll need to think about making that configurable on a per model basis and then making sure the rest of the code uses that instead of the default "id".

Makes sense?

**Comment by lancejpollard** [comment]
Sounds great!  I'll do just that.

**Comment by dima** [comment]
Not a bug
