### ISSUE TITLE
Improve sync pull performance

### ISSUE THREAD

**Issue by dima** [dima/restfulx_framework#3]
Rx pull at the moment pulls _everything_ from the server. This needs to be improved to only sync the things that changed.

**Comment by ximus** [comment]
Hi, my notes on the matter:
- From looking at the trace log, the biggest performance hole seems to be writing to the sqlite db.
- To keep the UI from becoming un responsive because of the data processing amd writing to sqlite, threads would be the answer. Since they don't exist in as3, these guys (see links at end) posted homegrown approaches to the matter (using timers and such). 

Hope it helps, Max

http://blog.generalrelativity.org/actionscript-30/green-threads/
http://blogs.adobe.com/aharui/2008/01/threads_in_actionscript_3.html
http://anirudhs.chaosnet.org/blog/2008.01.16.html

**Comment by dima** [comment]
Thanks Max,

I am currently more concerned with reducing the dataset that is being pulled. Even considering XMPP to push changes to clients that can be online/offline :)

**Comment by dima** [comment]
Fixed
